apiVersion: v1
kind: Service
metadata:
  name: hbase-master-1
spec:
  selector:
    app: hbase-master
    server-id: "1"
  type: ClusterIP
  clusterIP: "10.254.33.1"
  ports:
    - name: rpc
      port: 60000
      targetPort: 60000
    - name: info
      port: 60001
      targetPort: 60001
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-master-2
spec:
  selector:
    app: hbase-master
    server-id: "2"
  type: ClusterIP
  clusterIP: "10.254.33.2"
  ports:
    - name: rpc
      port: 60000
      targetPort: 60000
    - name: info
      port: 60001
      targetPort: 60001
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-region-1
spec:
  selector:
    app: hbase-region
    server-id: "1"
  type: ClusterIP
  clusterIP: "10.254.33.3"
  ports:
    - name: rpc
      port: 60010
      targetPort: 60010
    - name: info
      port: 60011
      targetPort: 60011
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-region-2
spec:
  selector:
    app: hbase-region
    server-id: "2"
  type: ClusterIP
  clusterIP: "10.254.33.4"
  ports:
    - name: rpc
      port: 60010
      targetPort: 60010
    - name: info
      port: 60011
      targetPort: 60011
---
apiVersion: v1
kind: Pod
metadata:
  name: hbase-master-1-pod
  labels:
    app: hbase-master
    server-id: "1"
spec:
  containers:
    - name: hbase-master-1
      image: index.caicloud.io/caicloud/hbase:sohu
      imagePullPolicy: Always
      ports:
        - containerPort: 60000
        - containerPort: 60001
      env:
        - name: HBASE_SERVER_TYPE
          value: master
        - name: HBASE_MASTER_PORT
          value: "60000"
        - name: HBASE_MASTER_INFO_PORT
          value: "60001"
        - name: HBASE_REGION_PORT
          value: "60010"
        - name: HBASE_REGION_INFO_PORT
          value: "60011"
        - name: HDFS_SERVICE
          value: "hadoop-namenode"
        - name: HDFS_PORT
          value: "8020"
        - name: ZOOKEEPER_SERVICE_LIST
          value: "zookeeper-1,zookeeper-2,zookeeper-3"
        - name: ZOOKEEPER_PORT
          value: "2181"
        - name: ZNODE_PARENT
          value: hbase
        - name: HBASE_MASTER_LIST
          value: "10.254.33.2:hbase-master-2"
        - name: HBASE_REGION_LIST
          value: "10.254.33.3:hbase-region-1 10.254.33.4:hbase-region-2"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: hbase-master-2-pod
  labels:
    app: hbase-master
    server-id: "2"
spec:
  containers:
    - name: hbase-master-1
      image: index.caicloud.io/caicloud/hbase:sohu
      imagePullPolicy: Always
      ports:
        - containerPort: 60000
        - containerPort: 60001
      env:
        - name: HBASE_SERVER_TYPE
          value: master
        - name: HBASE_MASTER_PORT
          value: "60000"
        - name: HBASE_MASTER_INFO_PORT
          value: "60001"
        - name: HBASE_REGION_PORT
          value: "60010"
        - name: HBASE_REGION_INFO_PORT
          value: "60011"
        - name: HDFS_SERVICE
          value: "hadoop-namenode"
        - name: HDFS_PORT
          value: "8020"
        - name: ZOOKEEPER_SERVICE_LIST
          value: "zookeeper-1,zookeeper-2,zookeeper-3"
        - name: ZOOKEEPER_PORT
          value: "2181"
        - name: ZNODE_PARENT
          value: hbase
        - name: HBASE_MASTER_LIST
          value: "10.254.33.1:hbase-master-1"
        - name: HBASE_REGION_LIST
          value: "10.254.33.3:hbase-region-1 10.254.33.4:hbase-region-2"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
    name: hbase-region-1-pod
    labels:
      app: hbase-region-1
      server-id: "1"
spec:
  containers:
    - name: hbase-region-1
      image: index.caicloud.io/caicloud/hbase:sohu
      imagePullPolicy: Always
      ports:
        - containerPort: 60010
        - containerPort: 60011
      env:
        - name: HBASE_SERVER_TYPE
          value: regionserver
        - name: HBASE_MASTER_PORT
          value: "60000"
        - name: HBASE_MASTER_INFO_PORT
          value: "60001"
        - name: HBASE_REGION_PORT
          value: "60010"
        - name: HBASE_REGION_INFO_PORT
          value: "60011"
        - name: HDFS_SERVICE
          value: "hadoop-namenode"
        - name: HDFS_PORT
          value: "8020"
        - name: ZOOKEEPER_SERVICE_LIST
          value: "zookeeper-1,zookeeper-2,zookeeper-3"
        - name: ZOOKEEPER_PORT
          value: "2181"
        - name: ZNODE_PARENT
          value: hbase
        - name: HBASE_MASTER_LIST
          value: "10.254.33.1:hbase-master-1 10.254.33.2:hbase-master-2"
        - name: HBASE_REGION_LIST
          value: "10.254.33.4:hbase-region-2"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
    name: hbase-region-2-pod
    labels:
      app: hbase-region-2
      server-id: "2"
spec:
  containers:
    - name: hbase-region-2
      image: index.caicloud.io/caicloud/hbase:sohu
      imagePullPolicy: Always
      ports:
        - containerPort: 60010
        - containerPort: 60011
      env:
        - name: HBASE_SERVER_TYPE
          value: regionserver
        - name: HBASE_MASTER_PORT
          value: "60000"
        - name: HBASE_MASTER_INFO_PORT
          value: "60001"
        - name: HBASE_REGION_PORT
          value: "60010"
        - name: HBASE_REGION_INFO_PORT
          value: "60011"
        - name: HDFS_SERVICE
          value: "hadoop-namenode"
        - name: HDFS_PORT
          value: "8020"
        - name: ZOOKEEPER_SERVICE_LIST
          value: "zookeeper-1,zookeeper-2,zookeeper-3"
        - name: ZOOKEEPER_PORT
          value: "2181"
        - name: ZNODE_PARENT
          value: hbase
        - name: HBASE_MASTER_LIST
          value: "10.254.33.1:hbase-master-1 10.254.33.2:hbase-master-2"
        - name: HBASE_REGION_LIST
          value: "10.254.33.3:hbase-region-1"
  restartPolicy: Always
